version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: |
          docker build .